# Generated by Django 2.2 on 2019-04-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=200)),
                ('session_key', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=50)),
                ('QQ', models.CharField(max_length=50)),
                ('authenticated', models.BooleanField()),
                ('card', models.ImageField(upload_to='img')),
            ],
        ),
    ]
