# Generated by Django 2.2 on 2019-04-21 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reward_title', models.CharField(max_length=100)),
                ('reward_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 4, 21, 20, 20, 42, 188173), verbose_name='date published')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='users.User')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.User')),
            ],
        ),
    ]
