# Generated by Django 2.2 on 2019-04-28 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_auto_20190421_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='prize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='static_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 28, 17, 5, 1, 87497), verbose_name='date published'),
        ),
    ]
