# Generated by Django 2.2 on 2019-04-28 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_auto_20190428_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='reward',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 28, 19, 44, 52, 910116), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='reward',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards.Classification'),
        ),
    ]
